# Generated by Django 4.2.1 on 2023-06-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employeeName', models.CharField(max_length=50)),
                ('employeeEmail', models.CharField(max_length=50)),
                ('employeePhoneNo', models.CharField(max_length=10)),
                ('employeeType', models.CharField(choices=[('Manager', 'manager'), ('Senior_Engineer', 'SE'), ('Junior Engineer', 'JE')], max_length=50)),
                ('employeeAddedDate', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
