# Generated by Django 4.2.1 on 2023-06-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employeeAge',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
